pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=build (macos-latest)
      - status-success=build (windows-latest)
      - status-success=build (ubuntu-latest)
    actions:
      merge:
        method: squash
