language: php
php:
- 7.3
install:
- composer install
env:
  global:
  - DB_HOST=localhost
  - DB_DATABASE=airtng
  - DB_USERNAME=postgres
  - APP_ENV=testing
  - APP_KEY=rJhIZXkdo3FtwqdDJsC7OadHIVhnarEE
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_NUMBER=+15552737123
before_script:
  - touch database/database-test.sqlite
  - php artisan migrate  --database=testing --force
