name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 3
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate --force
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: touch database/database-test.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan migrate --database=testing --force
        vendor/bin/phpunit
